name: Check

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  prek:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run prek
        uses: j178/prek-action@v2
